# OSP action
name: Optimal Stopping Point 

# Controls when the workflow will run
on:

  workflow_dispatch:
  # Allows you to run this workflow manually from the Actions tab
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: quay.io/aicoe/ocp-ci-analysis
      env:
        GITHUB_REPO: ${{ github.event.client_payload.REPO }}
        GITHUB_ORG: ${{ github.event.client_payload.ORG }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Jupyter Notebook
        run: jupyter nbconvert --to notebook --execute notebooks/access_github_ci_data.ipynb --TemplateExporter.exclude_input=True --ExecutePreprocessor.kernel_name='python3' --output 01_access_github_ci_data_notebook_executed
      - name: commit updated notebook 1
        uses: EndBug/add-and-commit@v7
